/**
 * This code was generated by Builder.io.
 */
import React from 'react';

export const ProductoContent: React.FC = () => {
  return (
    <>
      <h1 className="relative mt-6 ml-16 text-8xl leading-none text-center text-indigo-800 max-md:ml-2.5 max-md:text-4xl">
        Producto
      </h1>
      <p className="relative mt-2.5 ml-14 text-2xl font-bold text-slate-500 w-[389px] max-md:ml-2.5">
        Aquí encontraras programas de formación diseñados para que desarrolles tus habilidades con contenido flexible y práctico que te ayudará a alcanzar el éxito.
      </p>
    </>
  );
};