/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { ProductoContent } from './ProductoContent';

interface ProductoSectionProps {
  logoSrc: string;
  backgroundSrc: string;
}

export const ProductoSection: React.FC<ProductoSectionProps> = ({ logoSrc, backgroundSrc }) => {
  return (
    <section className="flex relative flex-col items-start pt-3.5 pr-20 pb-20 pl-4 w-full min-h-[423px] max-md:pr-5 max-md:max-w-full">
      <img loading="lazy" src={backgroundSrc} alt="" className="object-cover absolute inset-0 size-full" />
      <img loading="lazy" src={logoSrc} alt="Producto logo" className="object-contain aspect-square w-[50px]" />
      <ProductoContent />
    </section>
  );
};