/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FooterProps {}

const Footer: React.FC<FooterProps> = () => {
  return (
    <footer className="flex flex-wrap gap-10 justify-between items-center max-w-full h-[62px] w-[1225px]">
      <p className="self-stretch my-auto text-sm leading-none text-center text-black">
        Grupo de la O © 2024. Todos los derechos reservados.
      </p>
      <div className="flex gap-10 justify-center items-center self-stretch px-3 py-2 my-auto">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/82ac405c62223b68f253203cf38da672ae96b6e1fed31cf5f9fca30af632b3c8?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 1" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/e5860665098aec7062489b49c08fbe6b4715516e32e8cf364a256882745b9869?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 2" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
      </div>
    </footer>
  );
};

export default Footer;