/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MetalifeButtonProps {
  src: string;
  alt: string;
  text: string;
}

const MetalifeButton: React.FC<MetalifeButtonProps> = ({ src, alt, text }) => {
  return (
    <div className="flex gap-5 items-center self-stretch py-10 pr-5 pl-9 my-auto w-80 leading-none text-center whitespace-nowrap rounded-xl bg-slate-500 min-h-[130px] min-w-[240px] max-md:pl-5">
      <img loading="lazy" src={src} alt={alt} className="object-contain shrink-0 self-stretch my-auto aspect-square w-[55px]" />
      <div className="self-stretch my-auto w-[193px]">{text}</div>
    </div>
  );
};

export default MetalifeButton;