/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import MetalifeButton from './MetalifeButton';

interface MetalifeButtonsProps {}

const MetalifeButtons: React.FC<MetalifeButtonsProps> = () => {
  const buttonData = [
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/4095d0dbe214a22bc7afe9131bad8b5c73943881d8a448c964da4e782e7c2a77?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Línea de la vida icon", text: "LÍNEA DE LA VIDA" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/c72834a2c890296fe605ce6dc24df2c6b58ac246384ccfc71476244060c771a8?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Acercamiento icon", text: "acercamiento" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/f14290318f0b9fdc091c1af3a84d8cc0951efcaa40aa0e3893122d78409fe510?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Detección de necesidades icon", text: "Detección de necesidades" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/5f51b9427efb17a52b89342a9b4fd0a1ba620a1c044f44ba2195d338c9c3bc21?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Servicio post-venta icon", text: "Servicio post-venta" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d09977f789e290f28405a49557051235785f6d6fe7e313f24f4368f97201f991?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Prospección icon", text: "Prospección" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/4529d6da06870ea3a91d1cefe38fbc60a17b0347376b86b7f4b5986d3574c536?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Solución icon", text: "Solución" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/6ded4b171b527555ee96799006ec1e63f22199143174a31e611cb049bee642da?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Cierre icon", text: "Cierre" },
  ];

  return (
    <section className="flex flex-col justify-center w-full text-4xl text-white max-w-[1392px] min-h-[473px] max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-center items-center pt-8 w-full max-md:max-w-full">
        {buttonData.slice(0, 3).map((button, index) => (
          <MetalifeButton key={index} src={button.src} alt={button.alt} text={button.text} />
        ))}
      </div>
      <div className="flex flex-wrap gap-10 justify-center items-center mt-8 w-full max-md:max-w-full">
        {buttonData.slice(3, 6).map((button, index) => (
          <MetalifeButton key={index + 3} src={button.src} alt={button.alt} text={button.text} />
        ))}
      </div>
      <div className="flex justify-center mt-8">
        <MetalifeButton src={buttonData[6].src} alt={buttonData[6].alt} text={buttonData[6].text} />
      </div>
    </section>
  );
};

export default MetalifeButtons;