/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SidebarProps {}

const Sidebar: React.FC<SidebarProps> = () => {
  const menuItems = [
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/ef43e96168150d217db4668755e35469a518aa9f3a1c27a9fa4965034ab1c173?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 1" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/643b6db2ab412c51032be45694ca8794804895cd06668305075cd5ee2b47ace3?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 2" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/8fcef0ec093d9345684963205c06023f50f465975e5747ab30bfd1ba624265d6?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 3" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/e76c1fc7e8df77e6b6c39e5197d16b17ae37daee4c34a4b65f244635b31a72b6?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 4" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/7e935e45f837772f38b40b4bf45d64d0074e3183a49cf0bcaab3e23da784bf84?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 5" },
    { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/b1052fc89f21eb314914886ce610dfd8557c769b2acb64dc2f1b14a30e53571b?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 6" },
  ];

  return (
    <nav className="flex flex-col pt-24 w-[120px]">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d8099799d192c4d813c7486e8cc86a6607e04166e3454e418fa9193bb1f60665?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Logo" className="object-contain z-10 self-center aspect-[1.72] w-[62px]" />
      <div className="flex relative flex-col px-4 pt-52 pb-10 mt-0 rounded-none bg-slate-500 max-md:pt-24">
        <div className="flex z-0 flex-col w-full">
          {menuItems.map((item, index) => (
            <div key={index} className={`flex flex-col justify-center px-8 py-6 w-full rounded-3xl ${index === 4 ? 'bg-slate-50 bg-opacity-10' : 'bg-zinc-300 bg-opacity-0'} max-md:px-5`}>
              <div className="flex gap-4 items-center w-full">
                <img loading="lazy" src={item.src} alt={item.alt} className="object-contain self-stretch my-auto w-6 aspect-square" />
              </div>
            </div>
          ))}
        </div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/5ea92f383a9d1652478b00659513ed084f41a974b2232eaa8d73adbdad8b95f3?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Bottom sidebar image" className="object-contain z-0 mt-44 aspect-[0.61] rounded-[32px] w-[88px] max-md:mt-10" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/24fc8a3a6abd4ca9f1e541ad7b7a7f42772da130e8aa48cb04b7816b99a555b7?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Centered sidebar image" className="object-contain absolute left-2/4 z-0 -translate-x-2/4 aspect-square h-[45px] top-[21px] translate-y-[0%] w-[45px]" />
      </div>
    </nav>
  );
};

export default Sidebar;