/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TitleProps {}

const Title: React.FC<TitleProps> = () => {
  return (
    <section className="flex flex-col max-w-full w-[1393px]">
      <div className="flex relative flex-col items-start py-4 pr-20 pl-4 w-full min-h-[423px] max-md:pr-5 max-md:max-w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/73544e6a6685094a64c47ee66cd307078bfa4b9586dd8964d7dc7c02ecdb2c20?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Background" className="object-cover absolute inset-0 size-full" />
        <div className="flex relative gap-2 items-start text-8xl text-indigo-800 leading-[90px] max-md:text-4xl max-md:leading-10">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/619c8c5387f9c7d5c12523cea11941ff9378cde097922e67357ef8f201de0159?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Title icon" className="object-contain shrink-0 self-start aspect-square w-[50px]" />
          <h1 className="flex-auto self-end mt-7 max-md:text-4xl max-md:leading-10">
            Ciclo de <br /> la venta
          </h1>
        </div>
        <p className="relative mt-1 ml-14 text-2xl font-bold text-slate-500 w-[389px] max-md:ml-2.5">
          Esta formación te brindará técnicas prácticas y estrategias clave para optimizar cada interacción y mejorar tus resultados ¡Convierte cada prospecto en una venta segura!
        </p>
      </div>
    </section>
  );
};

export default Title;