/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-wrap gap-10 justify-between items-center mt-10 max-w-full w-[1225px]">
      <p className="self-stretch my-auto text-sm leading-none text-center text-black">
        Grupo de la O © 2024. Todos los derechos reservados.
      </p>
      <div className="flex gap-10 justify-center items-center self-stretch px-3 py-2 my-auto">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/7fc34ad97e9ff1e5b2472af151f4cfdf9b052540585a56d592226f76c45cbbc5?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 1" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/69a07defb23b4ee74363c8f23834b97283bf72fe5c7bc5e8ac2fce9c83fc3833?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 2" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
      </div>
    </footer>
  );
};

export default Footer;