/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Sidebar from './Sidebar';
import Section from './Section';
import Footer from './Footer';

const Menu: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-wrap items-start bg-gray-200">
      <Sidebar />
      <Section />
      <Footer />
    </div>
  );
};

export default Menu;