/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface OptionFrameProps {
  title: string;
  image: string;
}

const OptionFrame: React.FC<OptionFrameProps> = ({ title, image }) => {
  return (
    <div className="flex relative flex-col max-w-full whitespace-nowrap rounded-xl aspect-[0.794] w-[281px] max-md:text-4xl max-md:leading-10">
      <img loading="lazy" src={image} alt={title} className="object-cover absolute inset-0 size-full" />
      <div className="relative px-12 pt-64 pb-2 rounded-xl border-4 border-indigo-800 border-solid max-md:px-5 max-md:pt-24 max-md:text-4xl max-md:leading-10">
        {title.split(' ').map((word, index) => (
          <React.Fragment key={index}>
            {word}
            <br />
          </React.Fragment>
        ))}
      </div>
    </div>
  );
};

export default OptionFrame;