/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const ProductButton: React.FC = () => {
  return (
    <button className="flex shrink-0 self-stretch my-auto rounded-xl h-[350px] min-w-[240px] w-[277px]" aria-label="Product">
      {/* Content for product button */}
    </button>
  );
};

export default ProductButton;