/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import ProductsGrid from './ProductsGrid';

const Section: React.FC = () => {
  return (
    <section className="flex flex-col grow shrink items-center min-h-[985px] min-w-[240px] w-[1368px] max-md:max-w-full">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/5880ee7c20580604cda5d6086c3fe4907d0d67b721a502be68e8b274a8d8b9ac?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Section header" className="object-contain max-w-full aspect-[16.13] w-[1392px]" />
      <ProductsGrid />
    </section>
  );
};

export default Section;