/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col grow shrink w-24">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d6148586553c29d143941b58ce7c0a7d8d3cccbc42a3005bcdd91d9814952452?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Sidebar logo" className="object-contain aspect-[0.15] w-[120px]" />
    </aside>
  );
};

export default Sidebar;