/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import MetalifeButton from './MetalifeButton';

interface ButtonData {
  imageSrc: string;
  alt: string;
  text: string;
}

const buttonData: ButtonData[] = [
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/01899f0e69100bbb1dffdd16b050544ae3162cfe4b46876a6857046cdb132079?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Sign now icon", text: "Sign now" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/652fb1d5252f73192255129625df64211dc9478fb5840aa6cbfdaae1967a2740?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Cotizador icon", text: "cotizador" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/1c41b1b4ced80d7fa52966894b671df22ee900d57b150020f08b17f2ed49df81?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Cobranza icon", text: "Cobranza" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/2228c3bec906e7fdff971057108f8abdfa92d75563faf3fee5ba2524b7c77443?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "SUD icon", text: "sud" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/cdfa085b5439c241303f05e399713a09b4718244dd582179694fde3b01f653ab?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Front Metalife icon", text: "front\nmetalife" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/7a520d0ad45aedb43af660247126971450135e2077008dd5025658441d529e48?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Portal de Agentes icon", text: "portal de\nagentes" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/87a5d912cd7b16d1f38fa587d34096d120271648fda651a55a84a6b22da0f9b5?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Portal SAP icon", text: "portal sap" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/fe40cc196a262dd00d6327e55c3e1b03f20d3e10f07ce20571a484e5023581f7?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Portal Clientes icon", text: "portal clientes" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/812e1603acb846d539f7e9d2136ed63c96a5dc57e321f1d065c0a327585426d2?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Renovaciones icon", text: "Renovaciones" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/1fe6b364c2d905f3ed0a92573e10db164bf2fb17b68817ccb700b93c1c38b3a8?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Suscripción y Emisiones icon", text: "Suscripción y emisiones" },
];

const InteractiveGrid: React.FC = () => {
  return (
    <section className="flex flex-col justify-center w-full text-5xl text-white min-h-[568px] max-md:max-w-full max-md:text-4xl">
      <div className="flex flex-wrap gap-10 justify-center items-center w-full max-md:max-w-full max-md:text-4xl">
        {buttonData.slice(0, 9).map((button, index) => (
          <MetalifeButton key={index} imageSrc={button.imageSrc} alt={button.alt} text={button.text} />
        ))}
      </div>
      <div className="flex justify-center mt-8">
        <MetalifeButton imageSrc={buttonData[9].imageSrc} alt={buttonData[9].alt} text={buttonData[9].text} />
      </div>
    </section>
  );
};

export default InteractiveGrid;