/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MetalifeButtonProps {
  imageSrc: string;
  alt: string;
  text: string;
}

const MetalifeButton: React.FC<MetalifeButtonProps> = ({ imageSrc, alt, text }) => {
  return (
    <button className="flex gap-8 items-center self-stretch px-12 py-7 my-auto w-80 rounded-xl bg-slate-500 min-h-[106px] min-w-[240px] max-md:px-5 max-md:text-4xl">
      <img loading="lazy" src={imageSrc} alt={alt} className="object-contain shrink-0 self-stretch my-auto aspect-square w-[43px]" />
      <div className="self-stretch my-auto w-[193px] max-md:text-4xl">
        {text.split('\n').map((line, index) => (
          <React.Fragment key={index}>
            {line}
            {index < text.split('\n').length - 1 && <br />}
          </React.Fragment>
        ))}
      </div>
    </button>
  );
};

export default MetalifeButton;