/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MenuItem {
  imageSrc: string;
  alt: string;
}

const menuItems: MenuItem[] = [
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/ef43e96168150d217db4668755e35469a518aa9f3a1c27a9fa4965034ab1c173?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 1" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/643b6db2ab412c51032be45694ca8794804895cd06668305075cd5ee2b47ace3?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 2" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/0b43635dbf745673bbd98b114c70c3dfa56b14030b4f15bb824852cb1780aa96?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 3" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/e76c1fc7e8df77e6b6c39e5197d16b17ae37daee4c34a4b65f244635b31a72b6?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 4" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/ac2fbd760f6859a4e80d5c9648c3d8d09fd3899564e34b1fc2722cc08fc5ad0a?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 5" },
  { imageSrc: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/7a0287b38e1a8bfd55488c86720840748cd064ea36410cc77f3d86f06958f63b?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Menu item 6" },
];

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col grow shrink pt-24 w-24">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d8099799d192c4d813c7486e8cc86a6607e04166e3454e418fa9193bb1f60665?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Logo" className="object-contain z-10 self-center aspect-[1.72] w-[62px]" />
      <nav className="flex relative flex-col px-4 pt-52 pb-10 mt-0 rounded-none bg-slate-500 max-md:pt-24">
        <div className="flex z-0 flex-col w-full">
          {menuItems.map((item, index) => (
            <div key={index} className={`flex flex-col justify-center px-8 py-6 w-full rounded-3xl ${index === 2 ? 'bg-slate-50 bg-opacity-10' : 'bg-zinc-300 bg-opacity-0'} max-md:px-5`}>
              <div className="flex gap-4 items-center w-full">
                <img loading="lazy" src={item.imageSrc} alt={item.alt} className="object-contain self-stretch my-auto w-6 aspect-square" />
              </div>
            </div>
          ))}
        </div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/5ea92f383a9d1652478b00659513ed084f41a974b2232eaa8d73adbdad8b95f3?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Bottom decoration" className="object-contain z-0 mt-44 aspect-[0.61] rounded-[32px] w-[88px] max-md:mt-10" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/24fc8a3a6abd4ca9f1e541ad7b7a7f42772da130e8aa48cb04b7816b99a555b7?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Top decoration" className="object-contain absolute left-2/4 z-0 -translate-x-2/4 aspect-square h-[45px] top-[21px] translate-y-[0%] w-[45px]" />
      </nav>
    </aside>
  );
};

export default Sidebar;