/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Title: React.FC = () => {
  return (
    <section className="flex flex-col w-full max-md:max-w-full">
      <div className="flex relative flex-col items-start pt-3.5 pr-20 pb-8 pl-4 w-full min-h-[423px] max-md:pr-5 max-md:max-w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/56a8dedfc32d36980acf2ccadaa51a25e87b990dea9a446f8f2cb6c572969015?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Background" className="object-cover absolute inset-0 size-full" />
        <div className="flex relative gap-2 items-start text-8xl text-indigo-800 leading-[90px] max-md:text-4xl max-md:leading-10">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/7528c8ac816f08a4897cf5bbde49b2d33c43132c62aa0ad37ce4c8cb0f1454f6?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Icon" className="object-contain shrink-0 aspect-square w-[50px]" />
          <h1 className="flex-auto mt-5 max-md:text-4xl max-md:leading-10">
            Procesos <br /> operativos
          </h1>
        </div>
        <p className="relative ml-14 text-2xl font-bold text-slate-500 w-[389px] max-md:ml-2.5">
          Encuentra todas las herramientas clave para gestionar tu día a día como agente. Aquí tienes acceso rápido a los recursos que facilitan tu trabajo y optimizan tus resultados.
        </p>
      </div>
    </section>
  );
};

export default Title;