/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex overflow-hidden flex-col justify-center px-11 py-5 w-full max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center w-full max-md:max-w-full">
        <p className="self-stretch my-auto text-2xl leading-none text-center text-black w-[607px] max-md:max-w-full">
          Grupo de la O © 2022. Todos los derechos reservados.
        </p>
        <div className="flex gap-7 items-center self-stretch my-auto">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/82ac405c62223b68f253203cf38da672ae96b6e1fed31cf5f9fca30af632b3c8?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social Media Icon 1" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/e5860665098aec7062489b49c08fbe6b4715516e32e8cf364a256882745b9869?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social Media Icon 2" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
        </div>
      </div>
    </footer>
  );
};

export default Footer;