/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Header: React.FC = () => {
  return (
    <header className="flex overflow-hidden flex-col justify-center items-start py-7 w-full bg-slate-500 max-md:pr-5 max-md:max-w-full">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/971088f9183115de5ed920c5988163383e4dc3130e50f5b8c55eacb4cdd5eb8f?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Company Logo" className="object-contain max-w-full aspect-[3.73] w-[351px]" />
    </header>
  );
};

export default Header;