/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import LoginForm from './LoginForm';
import Footer from './Footer';

const LoginPage: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-gray-200">
      <Header />
      <main className="flex overflow-hidden flex-col w-full text-center text-white max-md:max-w-full">
        <section className="flex relative flex-col w-full min-h-[740px] max-md:max-w-full">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d6f773c7e906288641859499ba778718eca37d3d501f9f8aca573c3c510e3aa4?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="" className="object-cover absolute inset-0 size-full" />
          <div className="flex relative flex-wrap gap-10 justify-center items-center w-full min-h-[740px] max-md:max-w-full">
            <h1 className="self-stretch my-auto leading-[188px] text-[200px] w-[653px] max-md:max-w-full max-md:text-4xl max-md:leading-10">
              APRENDE Y DESTACA
            </h1>
            <LoginForm />
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default LoginPage;