/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const LoginForm: React.FC = () => {
  return (
    <form className="flex flex-col justify-center self-stretch my-auto min-w-[240px] w-[468px] max-md:max-w-full">
      <div className="flex flex-col w-full text-3xl tracking-widest max-md:max-w-full">
        <div className="flex flex-col w-full whitespace-nowrap max-md:max-w-full">
          <label htmlFor="username" className="overflow-hidden gap-2.5 self-stretch px-10 py-px max-w-full rounded-xl bg-slate-500 min-h-[40px] w-[171px] max-md:px-5">
            Usuario
          </label>
          <input
            type="text"
            id="username"
            className="flex w-full rounded-xl border-solid bg-stone-200 border-[3px] border-slate-500 min-h-[67px] max-md:max-w-full"
            aria-label="Usuario"
          />
        </div>
        <div className="flex flex-col mt-8 w-full whitespace-nowrap max-md:max-w-full">
          <label htmlFor="password" className="gap-2.5 self-stretch px-4 py-px max-w-full rounded-xl bg-slate-500 min-h-[40px] w-[171px]">
            Contraseña
          </label>
          <input
            type="password"
            id="password"
            className="flex w-full rounded-xl border-solid bg-stone-200 border-[3px] border-slate-500 min-h-[67px] max-md:max-w-full"
            aria-label="Contraseña"
          />
        </div>
        <button type="submit" className="overflow-hidden gap-2.5 self-center px-14 py-3.5 mt-8 max-w-full rounded-xl bg-slate-500 min-h-[64px] w-[280px] max-md:px-5">
          Iniciar Sesión
        </button>
      </div>
      <div className="flex overflow-hidden flex-col mt-20 w-full text-xl max-md:mt-10 max-md:max-w-full">
        <div className="px-3.5 py-6 rounded-xl bg-slate-500 max-md:max-w-full">
          Para ingresar a todos los cursos de Grupo de la O es necesario iniciar sesión.
          <br />
          <br />
          <span className="font-semibold">
            Para generar un usuario y contraseña ponte en contacto con el área de soporte de la promotoría.
          </span>
        </div>
      </div>
    </form>
  );
};

export default LoginForm;