/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ButtonProps {
  src: string;
  alt: string;
  title: string;
  subtitle: string;
}

const MetalifeButton: React.FC<ButtonProps> = ({ src, alt, title, subtitle }) => (
  <div className="flex gap-8 justify-center items-center self-stretch py-px pr-6 pl-6 my-auto w-80 rounded-xl bg-slate-500 min-h-[200px] min-w-[240px] max-md:px-5">
    <img loading="lazy" src={src} alt={alt} className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square" />
    <div className="my-auto leading-10 w-[237px]">
      {title} <br />
      <span className="text-2xl font-light">{subtitle}</span>
    </div>
  </div>
);

const CicloVenta: React.FC = () => {
  const buttons: ButtonProps[] = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/a490ffe9b18898b0ddb157add033ce805b2384d7653e1b70bcbb4bd37bf16b1e?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&",
      alt: "New agent icon",
      title: "Cuaderno de Compensación",
      subtitle: "Agente nuevo sin experiencia"
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/5c2f4b3518a3c00569cce7a2033beea5d154e1075d65ce45a384beaa680064a0?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&",
      alt: "Growing agent icon",
      title: "Cuaderno de Compensación",
      subtitle: "Agente en crecimiento"
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/933639c7017512e85255ce4c087631f65f964c3b2222c03d59d711c5f73335f0?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&",
      alt: "Experienced agent icon",
      title: "Cuaderno de Compensación",
      subtitle: "Agente consolidado y nuevo con experiencia"
    }
  ];

  return (
    <section className="flex flex-col justify-center w-full text-4xl text-center text-white max-w-[1392px] min-h-[389px] max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-center items-center w-full max-md:max-w-full">
        {buttons.map((button, index) => (
          <MetalifeButton key={index} {...button} />
        ))}
      </div>
    </section>
  );
};

export default CicloVenta;