/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import CuadernoDeBono from './CuadernoDeBono';

describe('CuadernoDeBono', () => {
  test('renders without crashing', () => {
    render(<CuadernoDeBono />);
    expect(screen.getByText(/cuaderno de bono/i)).toBeInTheDocument();
  });

  test('renders all main sections', () => {
    render(<CuadernoDeBono />);
    expect(screen.getByRole('banner')).toBeInTheDocument(); // Header
    expect(screen.getByRole('complementary')).toBeInTheDocument(); // Sidebar
    expect(screen.getByRole('contentinfo')).toBeInTheDocument(); // Footer
  });
});