/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Sidebar from './Sidebar';
import Header from './Header';
import Title from './Title';
import CicloVenta from './CicloVenta';
import Footer from './Footer';

const CuadernoDeBono: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-wrap items-start bg-gray-200">
      <Sidebar />
      <div className="flex flex-col min-h-[1008px] min-w-[240px] w-[1393px] max-md:max-w-full">
        <Header />
        <Title />
        <CicloVenta />
        <Footer />
      </div>
    </div>
  );
};

export default CuadernoDeBono;