/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-wrap gap-10 justify-between items-center max-w-full w-[1225px]">
      <p className="self-stretch my-auto text-sm leading-none text-center text-black">
        Grupo de la O © 2024. Todos los derechos reservados.
      </p>
      <div className="flex gap-10 justify-center items-center self-stretch px-3 py-2 my-auto">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/95180c3d898f01384f32da5d39bc35f1a048c0eebee60756d067275b0d17fe4c?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 1" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/b2cff55bb74782bd68ec2857974e24df529614179f770e77172bf3f16e5df350?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Social media icon 2" className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]" />
      </div>
    </footer>
  );
};

export default Footer;