/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Title: React.FC = () => {
  return (
    <section className="flex flex-col justify-center py-0.5 max-w-full w-[1393px]">
      <div className="flex relative flex-col items-start pt-5 pr-20 pb-4 pl-4 w-full min-h-[423px] max-md:pr-5 max-md:max-w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/e88af955222f649d4b55c5a263981d4f67b15e4230b004b348e54749ae1dcb22?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Background" className="object-cover absolute inset-0 size-full" />
        <div className="flex relative gap-2 items-start text-8xl leading-none text-indigo-800 max-md:text-4xl">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/470fe9ca05cc6947e8f35e5ba0a9a8af07a2e041d0298982ce5269f6fbfbe953?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Icon" className="object-contain shrink-0 self-start aspect-square w-[50px]" />
          <h1 className="flex-auto self-end mt-9 max-md:text-4xl">
            cuaderno <br /> de bono
          </h1>
        </div>
        <p className="relative mt-4 ml-16 text-2xl font-bold text-slate-500 w-[389px] max-md:ml-2.5">
          Asegúrate de aprovechar al máximo los beneficios de tu esfuerzo y motivación, mientras organizas de manera efectiva tus logros dentro de Grupo de la O. ¡Tu éxito siempre a la vista!
        </p>
      </div>
    </section>
  );
};

export default Title;