/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SessionButtonProps {
  src: string;
  alt: string;
  text: string;
}

const SessionButton: React.FC<SessionButtonProps> = ({ src, alt, text }) => (
  <button className="flex gap-1 justify-center items-center self-stretch py-3 pr-8 pl-8 my-auto rounded-xl bg-slate-500 min-h-[130px] min-w-[240px] w-[397px] max-md:px-5 max-md:text-4xl">
    <img loading="lazy" src={src} alt={alt} className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square" />
    <span className="self-stretch my-auto w-[283px] max-md:text-4xl">{text}</span>
  </button>
);

const sessions = [
  { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/ed3144f97a8aaf92efa3c32e7d61332d3a888bb678c12e809157a37aee28602a?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Session icon", text: "Sesión 28 Octubre" },
  { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/d9d249fbecc5cfb94abb95c2664eadde91cef2ccd0c8bc412ed7b066f15a77e3?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Session icon", text: "Sesión 21 Octubre" },
  { src: "https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/81278f45958603e35f0ef8baa943783fa8bde376554ab10d6c031d1081f1f5f2?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&", alt: "Session icon", text: "Sesión 7 Octubre" },
];

const OptionsGrid: React.FC = () => {
  return (
    <section className="flex flex-wrap gap-10 justify-center items-center w-full text-5xl text-center text-white min-h-[386px] max-md:max-w-full max-md:text-4xl">
      {sessions.map((session, index) => (
        <SessionButton key={index} {...session} />
      ))}
    </section>
  );
};

export default OptionsGrid;