/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Title: React.FC = () => {
  return (
    <section className="flex flex-col w-full max-md:max-w-full">
      <div className="flex relative flex-col items-start py-4 pr-20 pl-4 w-full min-h-[423px] max-md:pr-5 max-md:max-w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/b4f6af2e8157f84e02730e3287b634801c820f584a38587de9385a68512ab75a?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="" className="object-cover absolute inset-0 size-full" />
        <div className="flex relative items-start text-8xl text-indigo-800 leading-[90px] max-md:text-4xl max-md:leading-10">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/252dc4c4c2f04a6c8f8d7b124c5fb6f6/05ed6c1aab9b914b44096401ca535fb88bb4a2ae86e4fdcb2976c79c10f43ca6?apiKey=252dc4c4c2f04a6c8f8d7b124c5fb6f6&" alt="Title icon" className="object-contain shrink-0 self-start aspect-square w-[50px]" />
          <h1 className="flex-auto self-end mt-8 max-md:text-4xl max-md:leading-10">
            Capacitación <br /> de los lunes
          </h1>
        </div>
        <p className="relative ml-12 text-2xl font-bold text-slate-500 w-[389px] max-md:ml-2.5">
          Esta capacitación está diseñada para impulsar tu crecimiento profesional y ayudarte a alcanzar tus metas. Comienza tu semana con éxito y aprende de los mejores.
        </p>
      </div>
    </section>
  );
};

export default Title;